site_name: '🗂: `datacls`: Adds a little to dataclasses 🗂'

theme:
  name: material

  palette:
    primary:
      'blue'

  font:
    text:
      Roboto
    code:
      Roboto Mono

extra_css: [extra.css]

plugins:
    - mkdocstrings
