site_name: '🗂: `datacls`: Take the edge off `dataclass` 🗂'

theme:
  name: material

  palette:
    primary:
      'green'

  font:
    text:
      Roboto
    code:
      Roboto Mono

extra_css: [extra.css]

plugins:
    - mkdocstrings
