[tool.black]
line-length = 79
skip-string-normalization = true
target-version = ['py37']

[tool.doks]
auto = true

[tool.poetry]
authors = ["Tom Ritchford <tom@swirly.com>"]
description = "Slightly improved, backward compatible dataclasses"
homepage = "https://github.com/rec/datacls"
name = "datacls"
readme = "README.rst"
repository = "https://github.com/rec/datacls"
version = "4.5.0"

[tool.poetry.dependencies]
dtyper = "*"
python = ">=3.7"
xmod = "*"


[tool.poetry.group.dev.dependencies]
coverage = "*"
flake8 = "*"
pytest = "*"
versy = "*"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
